# Criado para testar o comando stress que testa os limites colocados no container.
# Olhar livro do descomplicando para ver o processo de uso do STRESS.

apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
  - name: girus
    image: ubuntu
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"